### ISSUE TITLE
excludeBundles doesn't work

### ISSUE THREAD

**Issue by infoitservit** [rmrevin/yii2-minify-view#47] opened 2016-12-14 14:43 UTC
Using your plugin i found that another extension, Dosamigos/Leaflet, doesn't work properly (leaflet.js has a bug that came out only when itd minified).
I tried to exclude the bundle asset but it doesn't work. I do it like this in the config file:

`'excludeBundles' => [
   \dosamigos\leaflet\LeafLetAsset::class,
 ],`

Am i using it wrong?

**Comment by rmrevin** [comment] 2016-12-23 15:59
Fixed in version `1.14.1`.
Thanks for issue.

**Closed by rmrevin** 2016-12-23 15:59 UTC

**Comment by farram** [comment] 2017-01-19 12:41
I also have the same problem. 
Version : 1.14.2
Conf :
'ExcludeBundles' => [
                'App\assets\PortfolioAsset',
             ],

**Comment by rmrevin** [comment] 2017-01-19 12:54
@farram Unfortunately, I do not have psychic abilities. I can not determine what the error without access to the code. You have to find the cause of the error and tell me about it, so I corrected it. Either create a demo git repository, which is reproduced your problem.
